esphome:
  name: smartaquarium

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "TP-Link_7958"
  password: "00436588"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Roomvadim Fallback Hotspot"
    password: "94JPAeDGO70m"

captive_portal:



output:
  - platform: gpio
    pin: GPIO2
    id: led

light:
  - platform: binary
    output: led
    name: "My LED"

# Example configuration entry
dallas:
  - pin: GPIO17 #23
    update_interval: 5s

# Individual sensors
sensor:
  - platform: dallas
    address: 0xdc0b2345e5437728
    name: "Температура"