esphome:
  name: vsuroom

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "SmartHome"
  password: "SmartHome"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Vsuroom Fallback Hotspot"
    password: "HkdWao66V0yl"

captive_portal:


# Example configuration entry for ESP32
i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

sensor:
  - platform: bmp280
    temperature:
      name: "Outside Temperature"
      oversampling: 16x
    pressure:
      name: "Outside Pressure"
    address: 0x76
    update_interval: 5s