esphome:
  name: room1

esp8266:
  board: esp01

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "12345678"

ota:
  password: "12345678"

wifi:
  ssid: "TP-Link_7958"
  password: "00436588"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Room1 Fallback Hotspot"
    password: "xb5fzynBlPAi"

captive_portal:
    